title: Shritesh
email: shritesh@shritesh.com
description: >
  Shritesh Bhattarai is a web developer and loves to build things.
baseurl: ""
url: ""
twitter_username: shritesh
github_username:  shritesh

markdown: kramdown
theme: overkyll-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /:title.html

timezone: America/Chicago

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
